name: build windows release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: OpenSourceVDI/gitlab-ci-run@HEAD
      - name: Uploading package_windows
        uses: ncipollo/release-action@v1
        with:
          artifacts: "package_windows"

