name: run gitlab pipelines
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - uses: OpenSourceVDI/gitlab-ci-run@HEAD
      - name: Uploading package_windows
        uses: actions/upload-artifact@v4
        with:
          name: package_windows
          path: package_windows
